using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Firebird3Demo.DAO.Map
{
    public static class FirebirdExtensions
    {
        public static PropertyBuilder<decimal?> HasPrecision(this PropertyBuilder<decimal?> builder, int precision, int scale)
        {
            return builder.HasColumnType($"decimal({precision},{scale})");
        }

        public static PropertyBuilder<decimal> HasPrecision(this PropertyBuilder<decimal> builder, int precision, int scale)
        {
            return builder.HasColumnType($"decimal({precision},{scale})");
        }

        public static PropertyBuilder<string> HasFixedLength(this PropertyBuilder<string> builder, int length)
        {
            return builder.HasColumnType($"char({length})");
        }

        public static PropertyBuilder<int> IsFBAutoGenerate(this PropertyBuilder<int> builder)
        {
            return builder.HasColumnType("INTEGER GENERATED BY DEFAULT AS IDENTITY");
        }

        public static PropertyBuilder<string> IsFBUUID(this PropertyBuilder<string> builder)
        {
            return builder.HasColumnType($"COMPUTED BY(GEN_UUID())");
        }
    }

}
